// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js"
import type { Database } from "./types"

const SUPABASE_URL = "https://nbliowysyxjyeckmznmq.supabase.co"
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ibGlvd3lzeXhqeWVja216bm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzEwMTAsImV4cCI6MjA2OTYwNzAxMH0.MPz19m5fh30Ms4FYhM92dC0VoWhW-TPs3Fm4LlkS97w"

const isBrowser = typeof window !== "undefined"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
    detectSessionInUrl: isBrowser,
  },
})
